In [62]:
import sys
import os

# Add the project root directory to sys.path
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))

In [63]:
from src.data import extract_data
from src.utils import init_hydra


cfg = init_hydra('main')
df, _ = extract_data('v1.0', cfg)
df = df.sample(n=10_000, random_state=42, ignore_index=True)
df

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,...,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2022-02-22,Capital Cargo International,PHF,CLT,False,False,901,859.0,0.0,-2.0,...,1010.0,1105.0,10.0,1043,32.0,1.0,2.0,1000-1059,2,0
1,2022-04-01,American Airlines Inc.,BWI,MIA,True,False,539,906.0,207.0,207.0,...,NaN,NaN,NaN,816,NaN,NaN,NaN,0800-0859,4,0
2,2022-04-17,Mesa Airlines Inc.,LGA,IAH,False,False,1400,1359.0,0.0,-1.0,...,1417.0,1651.0,5.0,1719,-23.0,0.0,-2.0,1700-1759,6,0
3,2022-04-12,Southwest Airlines Co.,DEN,COS,False,False,825,836.0,11.0,11.0,...,847.0,908.0,6.0,915,-1.0,0.0,-1.0,0900-0959,1,0
4,2022-04-06,Southwest Airlines Co.,SJC,LAX,False,False,905,900.0,0.0,-5.0,...,910.0,1003.0,6.0,1025,-16.0,0.0,-2.0,1000-1059,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022-02-02,Southwest Airlines Co.,PHX,LAX,False,False,1440,1440.0,0.0,0.0,...,1454.0,1452.0,4.0,1505,-9.0,0.0,-1.0,1500-1559,2,0
9996,2022-04-25,Spirit Air Lines,PHL,TPA,False,False,720,705.0,0.0,-15.0,...,717.0,929.0,5.0,1008,-34.0,0.0,-2.0,1000-1059,4,0
9997,2022-02-06,SkyWest Airlines Inc.,BZN,LAX,False,False,1820,1813.0,0.0,-7.0,...,1824.0,1929.0,6.0,2008,-33.0,0.0,-2.0,2000-2059,4,0
9998,2022-04-08,American Airlines Inc.,EWR,MIA,False,False,611,615.0,4.0,4.0,...,637.0,926.0,10.0,920,16.0,1.0,1.0,0900-0959,5,0
9999,2022-04-19,American Airlines Inc.,SEA,DFW,False,False,1145,1213.0,28.0,28.0,...,1233.0,1806.0,5.0,1741,30.0,1.0,2.0,1700-1759,7,0

In [64]:
df.to_csv('../tests/samples/test.csv')

In [65]:
import pandas as pd
from src.data import preprocess_data


X, y = preprocess_data(cfg, df)
df_transformed = pd.concat([X, y], axis=1).sort_index().round(6)

In [66]:
df_transformed.to_csv('../tests/samples/test_transformed.csv', index=False)

In [67]:
df_transformed.compare(pd.read_csv("../tests/samples/test_transformed.csv"))

Empty DataFrame
Columns: []
Index: []

In [71]:
read = pd.read_csv("../tests/samples/test_transformed.csv")

result = df_transformed.describe().compare(read.describe())

result.shape

(0, 0)